// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios; // Hata veren yer düzeltildi
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_s_voMQQJ9Zt_efU5gGV8Vsmdvtz8hc',
    appId: '1:885686922988:android:69d500c134f30579c77fc9',
    messagingSenderId: '885686922988',
    projectId: 'humea-a92e9',
    storageBucket: 'humea-a92e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyCKBwGA_Ouf25zBESglyrcSeluWTmi9_mI', // GoogleService-Info.plist dosyanızdaki API_KEY
    appId:
        '1:885686922988:ios:cbe662337710071dc77fc9', // GoogleService-Info.plist'teki GOOGLE_APP_ID
    messagingSenderId: '885686922988',
    projectId: 'humea-a92e9',
    storageBucket: 'humea-a92e9.firebasestorage.app',
    iosBundleId: 'com.hp.humea',
  );
}
